CREATE TABLE public.facility (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	facility_construction_status int4 NULL,
	facility_name varchar(255) NULL,
	naic_code varchar(255) NULL,
	facility_category varchar(255) NULL,
	facility_type varchar(255) NULL,
	target_saving varchar(255) NULL,
	display_pic_url text NULL,
	unit_number varchar(255) NULL,
	street_number varchar(255) NULL,
	street_name varchar(255) NULL,
	city varchar(255) NULL,
	country varchar(255) NULL,
	province varchar(255) NULL,
	postal_code varchar(255) NULL,
	address varchar(255) NULL,
	sector varchar(255) NULL,
	year_of_construction int4 NULL,
	gross_floor_area varchar(255) NULL,
	number_of_storeys int4 NULL,
	occupancy int4 NULL,
	number_of_building int4 NULL,
	company_id int4 NULL,
	facility_id_general_status int4 NULL,
	facility_id_submission_status int4 NULL,
	ng_distribution_company varchar(255) NULL,
	ng_distribution_company_data_extraction text NULL,
	longitude numeric NULL,
	latitude numeric NULL,
	facility_bas text NULL,
	facility_bas_connectivity bool NULL,
    -- new
    total_electricity_savings int4 NULL,
    energy_savings int4 NULL,
    total_incentive_earned int4 NULL,
    benchmarking_eui int4 NULL,
    facility_nickname varchar(255) NULL,
    -- new
	is_approved bool NULL,
	approved_by int4 NULL,
	is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT facility_pkey PRIMARY KEY (id)
)



CREATE TABLE public.facility_meter_detail (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT null,
	meter_name varchar(255) NULL,
    meter_type int4 NULL, -- 1 => electricity, 2 => natural gas, 3 => water
    meter_id int4 NULL,
    meter_active timestamp NULL,
    meter_inactive timestamp NULL,
    stil_in_use bool NULL,
    is_rg_meter bool NULL,
    meter_specification_url text NULL,
	is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
    purchased_from_the_grid bool NOT NULL DEFAULT false

	CONSTRAINT facility_meter_detail_pkey PRIMARY KEY (id)
)

CREATE TABLE public.facility_meter_monthly_entries (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT NULL,
    facility_meter_detail_id int4,
    meter_id int4 NULL,
    year int4 NULL,
    start_date timestamp NULL,
    end_date timestamp NULL,
    usage int4 NULL,
    demand int4 NULL,
    total_cost int4 NULL,
    last_updated varchar(255) NULL,
	is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT facility_meter_monthly_entries_pkey PRIMARY KEY (id)
)


















































    
    -- characterstics

    CREATE TABLE public.facility_characterstics (

    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT NULL

    operational_hours text NULL,
    year_of_construction int4 NULL,
    gross_floor_area varchar(255) NULL,
    number_of_storeys int4 NULL
    conditioned_gross_floor_area_including_common_area varchar(255) NULL,
    unonditioned_gross_floor_area varchar(255) NULL,

    unique_features_that_impact_energy_usage bool NULL,
    unique_features_of_facility text NULL,


    space_cooling_fuel_source varchar(255) NULL,
    space_cooling_technology varchar(255) NULL,
    space_heating_fuel_source varchar(255) NULL,
    water_heating_fuel_source varchar(255) NULL,
    water_heating_technology varchar(255) NULL,

    not_standard_hvac_equipment text NULL,

    
    -- space cooling
    space_cooling_technology_description varchar(255) NULL,
    space_cooling_technology_age int4 NULL,
    space_cooling_technology_capacity varchar(255) NULL,
    space_cooling_efficiency varchar(255) NULL,
    -- space heating
    space_heating_technology_description varchar(255) NULL,
    space_heating_technology_age int4 NULL,
    space_heating_technology_capacity varchar(255) NULL,
    space_heating_efficiency varchar(255) NULL,
    -- water heating
    water_heating_technology_description varchar(255) NULL,
    water_heating_technology_age int4 NULL,
    water_heating_technology_capacity varchar(255) NULL,
    water_heating_efficiency varchar(255) NULL,

    maximum_number_of_occupants int4 NULL,
    average_number_of_occupants int4 NULL,
    year_round_or_seasonal int4 NULL,
    occupants_months_detail text NULL,
   
    is_lighting_controlled_for_occupancy bool NULL,
    is_space_heating_controlled_for_occupancy bool NULL,
    is_space_cooling_controlled_for_occupancy bool NULL,


    facility_site_layout_media_url text NULL,
    facility_wall_assembly_and_ceiling_assembly_media_url text NULL,

    is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT facility_characterstics_pkey PRIMARY KEY (id)

    )

    
    
    
   

    -- Energy and water

    CREATE TABLE public.facility_energy_and_water_data (

    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT NULL

    is_tariff_class_greator_then_50kw bool NULL,
    is_facility_equipped_with_rg_meter bool NULL,
    not_equipped_with_rg_meter_description varchar(255) NULL,
    is_electricity_consumption_colloected_from_same_meter bool NULL,
    electricity_consumption_colloected_from_description varchar(255) NULL,
    is_on_site_generation_needs_to_be_removed bool NULL,
    on_site_generation_needs_to_be_removed_description varchar(255) NULL,

    electricity_consumption_meter_id varchar(255) NULL,
    electricity_consumption_start_date timestamp NULL,
    electricity_consumption_end_date timestamp NULL,
    electricity_consumption_media_url text NULL,

    electricity_consumption_on_site_generation_data varchar(255) NULL,
    electricity_consumption_on_site_generation_start_date timestamp NULL,
    electricity_consumption_on_site_generation_end_date timestamp NULL,
    electricity_consumption_on_site_generation_media_url text NULL,

    electricity_bill_electric_utility varchar(255) NULL,
    electricity_bill_rate_class varchar(255) NULL,
    electricity_bill_media_url text NULL,

    ng_consumption_start_date timestamp NULL,
    ng_consumption_end_date timestamp NULL,
    ng_consumption_total_consumption varchar(255) NULL,
    ng_consumption_natural_gas_utilit varchar(255) NULL,
    ng_consumption_media_url text NULL,

    water_consumption_start_date timestamp NULL,
    water_consumption_end_date timestamp NULL,
    water_consumption_total_consumption varchar(255) NULL,
    water_consumption_water_utility varchar(255) NULL,
    water_consumption_media_url text NULL

    is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,

	CONSTRAINT facility_energy_and_water_data_pkey PRIMARY KEY (id)
    )

    -- Weather Data

    CREATE TABLE public.facility_weather_data (
        
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT NULL

    independent_variables_name varchar(255) NULL,
    independent_variables_description varchar(255) NULL,
    independent_variables_start_date timestamp NULL,
    independent_variables_end_date timestamp NULL,
    independent_variables_source varchar(255) NULL,

    is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT facility_weather_data_pkey PRIMARY KEY (id)
    )

    -- report and studies

    CREATE TABLE public.facility_report_and_studies_data (

    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT NULL

    measure_report_file_url text NULL,
    measure_report_initiative_name varchar(255) NULL,
    measure_report_initiative_description varchar(255) NULL,
    measure_report_start_date timestamp NULL,
    measure_report_end_date timestamp NULL,
    measure_report_energy_saving_plan varchar(255) NULL,
    measure_report_initiative_project_scope_document_url text NULL,
    measure_report_initiative_cost_quote_document_url text NULL,
    measure_report_invoice_document_url text NULL,
    
    study_assessment_name varchar(255) NULL,
    study_assessment_description varchar(255) NULL,
    study_assessment_start_date timestamp NULL,
    study_assessment_end_date timestamp NULL,
    study_assessment_cost varchar(255) NULL,

    study_assessment_report_file_url text NULL,
    study_assessment_project_scope_doc_url text NULL,
    study_assessment_cost_quote_doc_url text NULL,
    study_assessment_invoice_doc_url text NULL,

    is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT facility_report_and_studies_data_pkey PRIMARY KEY (id)
    )




    




    


    








	
