CREATE TABLE public.facility_meter_hourly_entries (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	facility_id int4 NOT NULL,
	facility_meter_detail_id int4 NULL,
	meter_id int4 NULL,
	"year" int4 NULL,
	"usage" int4 NULL,
    "month" int4 NULL,
	media_url text NULL,
	demand int4 NULL,
	total_cost int4 NULL,
	last_updated varchar(255) NULL,
	is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	
	CONSTRAINT facility_meter_hourly_entries_pkey PRIMARY KEY (id)
);