  CREATE TABLE public.participant_agreement (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    company_id int4 NOT NULL,

    unsigned_doc text NULL,
    upload_sign text NULL,
    is_signed bool NULL,
    signed_doc text NULL,
    status int4 NULL,
    signed_on timestamp NULL,

	is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT participant_agreement_pkey PRIMARY KEY (id)
)