
ALTER TABLE public.facility add total_electricity_savings int4 NULL, 
ALTER TABLE public.facility add energy_savings int4 null;
 ALTER TABLE public.facility ADD total_incentive_earned int4 null;
ALTER TABLE public.facility add benchmarking_eui int4 null;
ALTER TABLE public.facility add facility_nickname varchar(255) null;


CREATE TABLE public.facility_meter_detail (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT null,
	meter_name varchar(255) NULL,
    meter_type int4 NULL,
    meter_id int4 NULL,
    meter_active timestamp NULL,
    meter_inactive timestamp NULL,
    stil_in_use bool NULL,
    is_rg_meter bool NULL,
    meter_specification_url text NULL,
	is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT facility_meter_detail_pkey PRIMARY KEY (id)
)


CREATE TABLE public.facility_meter_monthly_entries (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT NULL,
    facility_meter_detail_id int4,
    meter_id int4 NULL,
    year int4 NULL,
    start_date timestamp NULL,
    end_date timestamp NULL,
    usage int4 NULL,
    demand int4 NULL,
    total_cost int4 NULL,
    last_updated varchar(255) NULL,
	is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT facility_meter_monthly_entries_pkey PRIMARY KEY (id)
)

ALTER TABLE public.facility_meter_detail ADD purchased_from_the_grid bool NOT NULL DEFAULT false;