
ALTER TABLE epp.facility add total_electricity_savings int4 null;
ALTER TABLE epp.facility add energy_savings int4 null;
 ALTER TABLE epp.facility ADD total_incentive_earned int4 null;
ALTER TABLE epp.facility add benchmarking_eui int4 null;
ALTER TABLE epp.facility add facility_nickname varchar(255) null;


CREATE TABLE epp.facility_meter_detail (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT null,
	meter_name varchar(255) NULL,
    meter_type int4 NULL,
    meter_id int4 NULL,
    meter_active timestamp NULL,
    meter_inactive timestamp NULL,
    stil_in_use bool NULL,
    is_rg_meter bool NULL,
    meter_specification_url text NULL,
	is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT facility_meter_detail_pkey PRIMARY KEY (id)
)


CREATE TABLE epp.facility_meter_monthly_entries (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT NULL,
    facility_meter_detail_id int4,
    meter_id int4 NULL,
    year int4 NULL,
    start_date timestamp NULL,
    end_date timestamp NULL,
    usage int4 NULL,
    demand int4 NULL,
    total_cost int4 NULL,
    last_updated varchar(255) NULL,

	is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT facility_meter_monthly_entries_pkey PRIMARY KEY (id)
)


CREATE TABLE epp.facility_characterstics (

    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    facility_id int4 NOT null,

    operational_hours text NULL,
    year_of_construction int4 NULL,
    gross_floor_area varchar(255) NULL,
    number_of_storeys int4 null,
    conditioned_gross_floor_area_including_common_area varchar(255) NULL,
    unonditioned_gross_floor_area varchar(255) NULL,

    unique_features_that_impact_energy_usage bool NULL,
    unique_features_of_facility text NULL,


    space_cooling_fuel_source varchar(255) NULL,
    space_cooling_technology varchar(255) NULL,
    space_heating_fuel_source varchar(255) NULL,
    water_heating_fuel_source varchar(255) NULL,
    water_heating_technology varchar(255) NULL,

    not_standard_hvac_equipment text NULL,

    
    -- space cooling
    space_cooling_technology_description varchar(255) NULL,
    space_cooling_technology_age int4 NULL,
    space_cooling_technology_capacity varchar(255) NULL,
    space_cooling_efficiency varchar(255) NULL,
    -- space heating
    space_heating_technology_description varchar(255) NULL,
    space_heating_technology_age int4 NULL,
    space_heating_technology_capacity varchar(255) NULL,
    space_heating_efficiency varchar(255) NULL,
    -- water heating
    water_heating_technology_description varchar(255) NULL,
    water_heating_technology_age int4 NULL,
    water_heating_technology_capacity varchar(255) NULL,
    water_heating_efficiency varchar(255) NULL,

    maximum_number_of_occupants int4 NULL,
    average_number_of_occupants int4 NULL,
    year_round_or_seasonal int4 NULL,
    occupants_months_detail text NULL,
   
    is_lighting_controlled_for_occupancy bool NULL,
    is_space_heating_controlled_for_occupancy bool NULL,
    is_space_cooling_controlled_for_occupancy bool NULL,


    facility_site_layout_media_url text NULL,
    facility_wall_assembly_and_ceiling_assembly_media_url text NULL,

    is_active int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT facility_characterstics_pkey PRIMARY KEY (id)

    )



ALTER TABLE epp.facility_characterstics ADD COLUMN gross_floor_area_size_category INT,
ADD COLUMN facility_electricity_service_size VARCHAR(255),
ADD COLUMN facility_service_entrance_voltage VARCHAR(255),
ADD COLUMN space_cooling_efficiency_unit VARCHAR(255),
ADD COLUMN space_heating_efficiency_unit VARCHAR(255),
ADD COLUMN water_heating_efficiency_unit VARCHAR(255),
ADD column space_heating_technology VARCHAR(255)


ALTER TABLE facility_meter_detail
ADD COLUMN meter_spec_as_per_measurement Boolean;

ALTER TABLE public.facility_meter_detail ADD unit varchar(255) NULL;
