//---------------------------------ADMIN FACILITY TYPES--------------------------------

export const FETCH_ADMIN_FACILITY_LIST_REQUEST = "FETCH_ADMIN_FACILITY_LIST_REQUEST";
export const FETCH_ADMIN_FACILITY_LIST_SUCCESS = "FETCH_ADMIN_FACILITY_LIST_SUCCESS";
export const FETCH_ADMIN_FACILITY_LIST_FAILURE = "FETCH_ADMIN_FACILITY_LIST_FAILURE";

export const DELETE_ADMIN_FACILITY_REQUEST = "DELETE_ADMIN_FACILITY_REQUEST";
export const DELETE_ADMIN_FACILITY_SUCCESS = "DELETE_ADMIN_FACILITY_SUCCESS";
export const DELETE_ADMIN_FACILITY_FAILURE = "DELETE_ADMIN_FACILITY_FAILURE";

export const ADD_ADMIN_FACILITY_CHARACTERISTICS_REQUEST = "ADD_ADMIN_FACILITY_CHARACTERISTICS_REQUEST";
export const ADD_ADMIN_FACILITY_CHARACTERISTICS_SUCCESS = "ADD_ADMIN_FACILITY_CHARACTERISTICS_SUCCESS";
export const ADD_ADMIN_FACILITY_CHARACTERISTICS_FAILURE = "ADD_ADMIN_FACILITY_CHARACTERISTICS_FAILURE";

export const FETCH_ADMIN_FACILITY_CHARACTERISTICS_REQUEST = "FETCH_ADMIN_FACILITY_CHARACTERISTICS_REQUEST";
export const FETCH_ADMIN_FACILITY_CHARACTERISTICS_SUCCESS = "FETCH_ADMIN_FACILITY_CHARACTERISTICS_SUCCESS";
export const FETCH_ADMIN_FACILITY_CHARACTERISTICS_FAILURE = "FETCH_ADMIN_FACILITY_CHARACTERISTICS_FAILURE";

export const UPDATE_ADMIN_FACILITY_CHARACTERISTICS_REQUEST = "UPDATE_ADMIN_FACILITY_CHARACTERISTICS_REQUEST";
export const UPDATE_ADMIN_FACILITY_CHARACTERISTICS_SUCCESS = "UPDATE_ADMIN_FACILITY_CHARACTERISTICS_SUCCESS";
export const UPDATE_ADMIN_FACILITY_CHARACTERISTICS_FAILURE = "UPDATE_ADMIN_FACILITY_CHARACTERISTICS_FAILURE";

//---------------------------------ADMIN METER TYPES--------------------------------

export const FETCH_ADMIN_METER_LIST_REQUEST = "FETCH_ADMIN_METER_LIST_REQUEST";
export const FETCH_ADMIN_METER_LIST_SUCCESS = "FETCH_ADMIN_METER_LIST_SUCCESS";
export const FETCH_ADMIN_METER_LIST_FAILURE = "FETCH_ADMIN_METER_LIST_FAILURE";

export const ADD_ADMIN_METER_REQUEST = "ADD_ADMIN_METER_REQUEST";
export const ADD_ADMIN_METER_SUCCESS = "ADD_ADMIN_METER_SUCCESS";
export const ADD_ADMIN_METER_FAILURE = "ADD_ADMIN_METER_FAILURE";

export const UPDATE_ADMIN_METER_REQUEST = "UPDATE_ADMIN_METER_REQUEST";
export const UPDATE_ADMIN_METER_SUCCESS = "UPDATE_ADMIN_METER_SUCCESS";
export const UPDATE_ADMIN_METER_FAILURE = "UPDATE_ADMIN_METER_FAILURE";

export const FETCH_ADMIN_METER_DETAILS_REQUEST = "FETCH_ADMIN_METER_DETAILS_REQUEST";
export const FETCH_ADMIN_METER_DETAILS_SUCCESS = "FETCH_ADMIN_METER_DETAILS_SUCCESS";
export const FETCH_ADMIN_METER_DETAILS_FAILURE = "FETCH_ADMIN_METER_DETAILS_FAILURE";

export const DELETE_ADMIN_METER_REQUEST = "DELETE_ADMIN_METER_REQUEST";
export const DELETE_ADMIN_METER_SUCCESS = "DELETE_ADMIN_METER_SUCCESS";
export const DELETE_ADMIN_METER_FAILURE = "DELETE_ADMIN_METER_FAILURE";

export const FETCH_ADMIN_METER_STATISTICS_REQUEST = "FETCH_ADMIN_METER_STATISTICS_REQUEST";
export const FETCH_ADMIN_METER_STATISTICS_SUCCESS = "FETCH_ADMIN_METER_STATISTICS_SUCCESS";
export const FETCH_ADMIN_METER_STATISTICS_FAILURE = "FETCH_ADMIN_METER_STATISTICS_FAILURE";