//---------------------------------ADMIN FACILITY TYPES--------------------------------

export const FETCH_ADMIN_FACILITY_LIST_REQUEST = "FETCH_ADMIN_FACILITY_LIST_REQUEST";
export const FETCH_ADMIN_FACILITY_LIST_SUCCESS = "FETCH_ADMIN_FACILITY_LIST_SUCCESS";
export const FETCH_ADMIN_FACILITY_LIST_FAILURE = "FETCH_ADMIN_FACILITY_LIST_FAILURE";

export const DELETE_ADMIN_FACILITY_REQUEST = "DELETE_ADMIN_FACILITY_REQUEST";
export const DELETE_ADMIN_FACILITY_SUCCESS = "DELETE_ADMIN_FACILITY_SUCCESS";
export const DELETE_ADMIN_FACILITY_FAILURE = "DELETE_ADMIN_FACILITY_FAILURE";