# Weather Query
weather_query = "select year, month, sum(temp),sum(rel_hum), sum(precip_amount),sum(wind_spd),sum(station_press)  from weather_data where facility_id = 336 group by year, month order by year, month"

# Summary Queries Start
# Outliers Query
outlier_summary = "SELECT e.meter_type, CASE WHEN e.meter_type = 1 THEN 'ELECTRICITY' WHEN e.meter_type = 2 THEN 'WATER' WHEN e.meter_type = 3 THEN 'NG' ELSE 'Unknown' END AS meter_name, COUNT(e.id) AS total_records, TO_CHAR(MIN(e.start_date), 'YYYY/MM/DD HH24:MI') AS time_stamp_start, TO_CHAR(MAX(e.end_date), 'YYYY/MM/DD HH24:MI') AS time_stamp_end, CASE WHEN e.reading < r.lower_bound THEN 'Lower limit' WHEN e.reading > r.upper_bound THEN 'Upper limit' ELSE 'Within bounds' END AS bound_type FROM epp.meter_hourly_entries e JOIN (SELECT meter_type, percentile_cont(0.25) WITHIN GROUP (ORDER BY reading) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) AS Q3, (percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) - percentile_cont(0.25) WITHIN GROUP (ORDER BY reading)) AS IQR, (percentile_cont(0.25) WITHIN GROUP (ORDER BY reading) - {} * (percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) - percentile_cont(0.25) WITHIN GROUP (ORDER BY reading))) AS lower_bound, (percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) + {} * (percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) - percentile_cont(0.25) WITHIN GROUP (ORDER BY reading))) AS upper_bound FROM meter_hourly_entries WHERE reading NOT IN (0, 'NaN') AND facility_id = {} GROUP BY meter_type) r ON e.meter_type = r.meter_type WHERE e.reading NOT IN (0, 'NaN') AND (e.reading < r.lower_bound OR e.reading > r.upper_bound) AND e.is_independent_variable = {} GROUP BY e.meter_type, meter_name, bound_type ORDER BY bound_type DESC, e.meter_type;"
temp_outlier_summary = "SELECT 'TEMPERATURE' AS meter_name, COUNT(w.id) AS total_records, TO_CHAR(MIN(w.date_time), 'YYYY/MM/DD HH24:MI') AS time_stamp_start, TO_CHAR(MAX(w.date_time + interval '1 hour'), 'YYYY/MM/DD HH24:MI') AS time_stamp_end, CASE WHEN w.temp < r.lower_bound THEN 'Lower limit' WHEN w.temp > r.upper_bound THEN 'Upper limit' ELSE 'Within bounds' END AS bound_type FROM weather_data w JOIN (SELECT percentile_cont(0.25) WITHIN GROUP (ORDER BY temp) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY temp) AS Q3, (percentile_cont(0.75) WITHIN GROUP (ORDER BY temp) - percentile_cont(0.25) WITHIN GROUP (ORDER BY temp)) AS IQR, (percentile_cont(0.25) WITHIN GROUP (ORDER BY temp) - {} * (percentile_cont(0.75) WITHIN GROUP (ORDER BY temp) - percentile_cont(0.25) WITHIN GROUP (ORDER BY temp))) AS lower_bound, (percentile_cont(0.75) WITHIN GROUP (ORDER BY temp) + {} * (percentile_cont(0.75) WITHIN GROUP (ORDER BY temp) - percentile_cont(0.25) WITHIN GROUP (ORDER BY temp))) AS upper_bound FROM weather_data WHERE facility_id = {} GROUP BY facility_id) r ON w.facility_id = {} WHERE w.temp NOT IN (0, 'NaN') AND (w.temp < r.lower_bound OR w.temp > r.upper_bound) GROUP BY meter_name, bound_type ORDER BY bound_type DESC;"

# Observed Data
observed_data_summary = "WITH quartiles AS (SELECT meter_type, percentile_cont(0.25) WITHIN GROUP (ORDER BY reading) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) AS Q3 FROM epp.meter_hourly_entries WHERE reading NOT IN (0, 'NaN') AND facility_id = {} GROUP BY meter_type), outlier_ranges AS (SELECT meter_type, Q1, Q3, (Q3 - Q1) AS IQR, (Q1 - {} * (Q3 - Q1)) AS lower_bound, (Q3 + {} * (Q3 - Q1)) AS upper_bound FROM quartiles) SELECT e.meter_type, CASE WHEN e.meter_type = 1 THEN 'ELECTRICITY' WHEN e.meter_type = 2 THEN 'WATER' WHEN e.meter_type = 3 THEN 'NG' ELSE 'Unknown' END AS meter_name, COUNT(e.id) AS total_records, TO_CHAR(MIN(e.start_date), 'YYYY/MM/DD HH24:MI') AS time_stamp_start, TO_CHAR(MAX(e.end_date), 'YYYY/MM/DD HH24:MI') AS time_stamp_end FROM meter_hourly_entries e JOIN outlier_ranges r ON e.meter_type = r.meter_type WHERE e.reading NOT IN (0, 'NaN') AND e.reading >= r.lower_bound AND e.reading <= r.upper_bound AND e.is_independent_variable = {} GROUP BY e.meter_type, meter_name ORDER BY e.meter_type;"
temp_observed_data_summary = "WITH quartiles AS (SELECT percentile_cont(0.25) WITHIN GROUP (ORDER BY temp) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY temp) AS Q3 FROM weather_data WHERE temp NOT IN (0, 'NaN') AND facility_id = {} GROUP BY facility_id), outlier_ranges AS (SELECT Q1, Q3, (Q3 - Q1) AS IQR, (Q1 - {} * (Q3 - Q1)) AS lower_bound, (Q3 + {} * (Q3 - Q1)) AS upper_bound FROM quartiles) SELECT 'TEMPERATURE' AS meter_name, COUNT(w.id) AS total_records, TO_CHAR(MIN(w.date_time), 'YYYY/MM/DD HH24:MI') AS time_stamp_start, TO_CHAR(MAX(w.date_time + interval '1 hour'), 'YYYY/MM/DD HH24:MI') AS time_stamp_end FROM weather_data w JOIN outlier_ranges r ON w.temp NOT IN (0, 'NaN') AND w.temp >= r.lower_bound AND w.temp <= r.upper_bound AND w.facility_id = {} GROUP BY meter_name;"

# Missing Data
missing_data_summary = "SELECT meter_type, CASE WHEN meter_type = 1 THEN 'ELECTRICITY' WHEN meter_type = 2 THEN 'WATER' WHEN meter_type = 3 THEN 'NG' ELSE 'Unknown' END AS meter_name, COUNT(id) AS total_records, TO_CHAR(MIN(start_date), 'YYYY/MM/DD HH24:MI') AS time_stamp_start, TO_CHAR(MAX(end_date), 'YYYY/MM/DD HH24:MI') AS time_stamp_end FROM epp.meter_hourly_entries WHERE facility_id = {} AND (reading = 0 OR reading = 'NaN' OR reading IS NULL) AND is_independent_variable = {} GROUP BY meter_name, meter_type ORDER BY meter_type;"
temp_missing_data_summary = "SELECT 'TEMPERATURE' AS meter_name, COUNT(id) AS total_records, TO_CHAR(MIN(date_time), 'YYYY/MM/DD HH24:MI') AS time_stamp_start, TO_CHAR(MAX(date_time + interval '1 hour'), 'YYYY/MM/DD HH24:MI') AS time_stamp_end FROM weather_data WHERE facility_id = {} AND (temp = 0 OR temp = 'NaN' OR temp IS NULL) GROUP BY meter_name;"

# Summary Queries Ends





# Temperature Data
temperature_data_summary = "WITH quartiles AS (SELECT percentile_cont(0.25) WITHIN GROUP (ORDER BY temp) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY temp) AS Q3 FROM weather_data WHERE temp NOT IN (0, 'NaN') AND facility_id = {}), outlier_ranges AS (SELECT Q1, Q3, (Q3 - Q1) AS IQR, (Q1 - {} * (Q3 - Q1)) AS lower_bound, (Q3 + {} * (Q3 - Q1)) AS upper_bound FROM quartiles) SELECT 'TEMPERATURE' AS meter_name, 104 AS meter_type, COUNT(id) AS total_records, MIN(date_time) AS start_date, MAX(date_time + INTERVAL '1 hour') AS end_date, TO_CHAR(MIN(date_time), 'YYYY/MM/DD HH24:MI') AS time_stamp_start, TO_CHAR(MAX(date_time + INTERVAL '1 hour'), 'YYYY/MM/DD HH24:MI') AS time_stamp_end, CASE WHEN temp < lower_bound THEN 'Lower limit' WHEN temp > upper_bound THEN 'Upper limit' END AS bound_type FROM weather_data JOIN outlier_ranges ON facility_id = {} AND temp NOT IN (0, 'NaN') AND (temp < lower_bound OR temp > upper_bound) GROUP BY meter_name, meter_type, bound_type ORDER BY bound_type DESC;"

# Outlier Detail

# upper_bound_outlier_detail = "WITH quartiles AS (SELECT percentile_cont(0.25) WITHIN GROUP (ORDER BY reading) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) AS Q3 FROM meter_hourly_entries WHERE reading NOT IN (0, 'NaN') AND facility_id = 336), outlier_ranges AS (SELECT Q1, Q3, (Q3 - Q1) AS IQR, (Q1 - 1.5 * (Q3 - Q1)) AS lower_bound, (Q3 + 1.5 * (Q3 - Q1)) AS upper_bound FROM quartiles) SELECT e.start_date, e.end_date, e.reading FROM meter_hourly_entries e JOIN outlier_ranges o ON e.facility_id = 336 WHERE e.reading NOT IN (0, 'NaN') AND (e.reading > o.upper_bound) AND e.is_independent_variable = False AND e.meter_type = 1 ORDER BY e.meter_type, e.start_date, e.end_date;"
upper_bound_outlier_detail = "WITH quartiles AS (SELECT percentile_cont(0.25) WITHIN GROUP (ORDER BY reading) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) AS Q3 FROM epp.meter_hourly_entries WHERE reading NOT IN (0, 'NaN') AND facility_id = {}), outlier_ranges AS (SELECT Q1, Q3, (Q3 - Q1) AS IQR, (Q1 - {} * (Q3 - Q1)) AS lower_bound,      (Q3 + {} * (Q3 - Q1)) AS upper_bound FROM quartiles) SELECT e.start_date, e.end_date, e.reading FROM meter_hourly_entries e JOIN outlier_ranges o ON e.facility_id = {} WHERE e.reading NOT IN (0, 'NaN') AND (e.reading > o.upper_bound) AND e.is_independent_variable = {} AND e.meter_type = {} ORDER BY e.meter_type, e.start_date, e.end_date;"

# lower_bound_outlier_detail = "WITH quartiles AS (SELECT percentile_cont(0.25) WITHIN GROUP (ORDER BY reading) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) AS Q3 FROM meter_hourly_entries WHERE reading NOT IN (0, 'NaN') AND facility_id = 336), outlier_ranges AS (SELECT Q1, Q3, (Q3 - Q1) AS IQR, (Q1 - 1.5 * (Q3 - Q1)) AS lower_bound, (Q3 + 1.5 * (Q3 - Q1)) AS upper_bound FROM quartiles) SELECT e.start_date, e.end_date, e.reading FROM meter_hourly_entries e JOIN outlier_ranges o ON e.facility_id = 336 WHERE e.reading NOT IN (0, 'NaN') AND (e.reading < o.lower_bound) AND e.is_independent_variable = False AND e.meter_type = 1 ORDER BY e.meter_type, e.start_date, e.end_date;"
lower_bound_outlier_detail = "WITH quartiles AS (SELECT percentile_cont(0.25) WITHIN GROUP (ORDER BY reading) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) AS Q3 FROM epp.meter_hourly_entries WHERE reading NOT IN (0, 'NaN') AND facility_id = 336), outlier_ranges AS (SELECT Q1, Q3, (Q3 - Q1) AS IQR, (Q1 - 1.5 * (Q3 - Q1)) AS lower_bound, (Q3 + 1.5 * (Q3 - Q1)) AS upper_bound FROM quartiles) SELECT e.start_date, e.end_date, e.reading FROM meter_hourly_entries e JOIN outlier_ranges o ON e.facility_id = 336 WHERE e.reading NOT IN (0, 'NaN') AND (e.reading < o.lower_bound) AND e.is_independent_variable = False AND e.meter_type = 1 ORDER BY e.meter_type, e.start_date, e.end_date;"

# Observed Data Detail
# observed_data_detail = "WITH quartiles AS (SELECT percentile_cont(0.25) WITHIN GROUP (ORDER BY reading) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) AS Q3 FROM meter_hourly_entries WHERE reading NOT IN (0, 'NaN') AND facility_id = 336), outlier_ranges AS (SELECT Q1, Q3, (Q3 - Q1) AS IQR, (Q1 - 1.5 * (Q3 - Q1)) AS lower_bound, (Q3 + 1.5 * (Q3 - Q1)) AS upper_bound FROM quartiles) SELECT e.start_date, e.end_date, e.reading FROM meter_hourly_entries e JOIN outlier_ranges o ON e.reading NOT IN (0, 'NaN') AND e.facility_id = 336 AND e.reading >= o.lower_bound AND e.reading <= o.upper_bound WHERE e.is_independent_variable = False AND e.meter_type = 1 ORDER BY e.start_date, e.end_date;"
observed_data_detail = "WITH quartiles AS (SELECT percentile_cont(0.25) WITHIN GROUP (ORDER BY reading) AS Q1, percentile_cont(0.75) WITHIN GROUP (ORDER BY reading) AS Q3 FROM epp.meter_hourly_entries WHERE reading NOT IN (0, 'NaN') AND facility_id =    {}), outlier_ranges AS (SELECT Q1, Q3, (Q3 - Q1) AS IQR, (Q1 - {} * (Q3 - Q1)) AS lower_bound, (Q3 + {} * (Q3 - Q1)) AS upper_bound FROM quartiles) SELECT e.start_date, e.end_date, e.reading FROM meter_hourly_entries e JOIN outlier_ranges o ON e.reading NOT IN (0, 'NaN') AND e.facility_id = {} AND e.reading >= o.lower_bound AND e.reading <= o.upper_bound WHERE e.is_independent_variable = {} AND e.meter_type = {} ORDER BY e.start_date, e.end_date limit 50;"

# MissingData
# missing_data_detail = "SELECT e.start_date, e.end_date, e.reading FROM meter_hourly_entries AS e WHERE e.reading IN (0, 'NaN') AND e.meter_type = 3 AND e.facility_id = 336 AND e.is_independent_variable = False;"
missing_data_detail = "SELECT e.start_date, e.end_date, e.reading FROM epp.meter_hourly_entries AS e WHERE e.reading IN (0, 'NaN') AND e.meter_type = {} AND e.facility_id = {} AND e.is_independent_variable = {};"
