//---------------------------------FACILITY TYPES--------------------------------

export const FETCH_FACILITY_LIST_REQUEST = "FETCH_FACILITY_LIST_REQUEST";
export const FETCH_FACILITY_LIST_SUCCESS = "FETCH_FACILITY_LIST_SUCCESS";
export const FETCH_FACILITY_LIST_FAILURE = "FETCH_FACILITY_LIST_FAILURE";

export const SUBMIT_FACILITY_FOR_APPROVAL_REQUEST =
  "SUBMIT_FACILITY_FOR_APPROVAL_REQUEST";
export const SUBMIT_FACILITY_FOR_APPROVAL_SUCCESS =
  "SUBMIT_FACILITY_FOR_APPROVAL_SUCCESS";
export const SUBMIT_FACILITY_FOR_APPROVAL_FAILURE =
  "SUBMIT_FACILITY_FOR_APPROVAL_FAILURE";

export const FETCH_FACILITY_DETAILS_REQUEST = "FETCH_FACILITY_DETAILS_REQUEST";
export const FETCH_FACILITY_DETAILS_SUCCESS = "FETCH_FACILITY_DETAILS_SUCCESS";
export const FETCH_FACILITY_DETAILS_FAILURE = "FETCH_FACILITY_DETAILS_FAILURE";

export const DELETE_FACILITY_REQUEST = "DELETE_FACILITY_REQUEST";
export const DELETE_FACILITY_SUCCESS = "DELETE_FACILITY_SUCCESS";
export const DELETE_FACILITY_FAILURE = "DELETE_FACILITY_FAILURE";

export const ADD_FACILITY_CHARACTERISTIC_REQUEST = "ADD_FACILITY_CHARACTERISTIC_REQUEST";
export const ADD_FACILITY_CHARACTERISTIC_SUCCESS = "ADD_FACILITY_CHARACTERISTIC_SUCCESS";
export const ADD_FACILITY_CHARACTERISTIC_FAILURE = "ADD_FACILITY_CHARACTERISTIC_FAILURE";

export const FETCH_FACILITY_CHARACTERISTICS_REQUEST = "FETCH_FACILITY_CHARACTERISTICS_REQUEST";
export const FETCH_FACILITY_CHARACTERISTICS_SUCCESS = "FETCH_FACILITY_CHARACTERISTICS_SUCCESS";
export const FETCH_FACILITY_CHARACTERISTICS_FAILURE = "FETCH_FACILITY_CHARACTERISTICS_FAILURE";

export const UPDATE_FACILITY_CHARACTERISTIC_REQUEST = "UPDATE_FACILITY_CHARACTERISTIC_REQUEST";
export const UPDATE_FACILITY_CHARACTERISTIC_SUCCESS = "UPDATE_FACILITY_CHARACTERISTIC_SUCCESS";
export const UPDATE_FACILITY_CHARACTERISTIC_FAILURE = "UPDATE_FACILITY_CHARACTERISTIC_FAILURE";

export const FETCH_FACILITY_STATUS_REQUEST = "FETCH_FACILITY_STATUS_REQUEST";
export const FETCH_FACILITY_STATUS_SUCCESS = "FETCH_FACILITY_STATUS_SUCCESS";
export const FETCH_FACILITY_STATUS_FAILURE = "FETCH_FACILITY_STATUS_FAILURE";

export const UPDATE_FACILITY_STATUS_REQUEST = "UPDATE_FACILITY_STATUS_REQUEST";
export const UPDATE_FACILITY_STATUS_SUCCESS = "UPDATE_FACILITY_STATUS_SUCCESS";
export const UPDATE_FACILITY_STATUS_FAILURE = "UPDATE_FACILITY_STATUS_FAILURE";

//---------------------------------METER TYPES--------------------------------
export const FETCH_METER_LIST_REQUEST = "FETCH_METER_LIST_REQUEST";
export const FETCH_METER_LIST_SUCCESS = "FETCH_METER_LIST_SUCCESS";
export const FETCH_METER_LIST_FAILURE = "FETCH_METER_LIST_FAILURE";

export const ADD_METER_REQUEST = "ADD_METER_REQUEST";
export const ADD_METER_SUCCESS = "ADD_METER_SUCCESS";
export const ADD_METER_FAILURE = "ADD_METER_FAILURE";

export const UPDATE_METER_REQUEST = "UPDATE_METER_REQUEST";
export const UPDATE_METER_SUCCESS = "UPDATE_METER_SUCCESS";
export const UPDATE_METER_FAILURE = "UPDATE_METER_FAILURE";

export const FETCH_METER_DETAILS_REQUEST = "FETCH_METER_DETAILS_REQUEST";
export const FETCH_METER_DETAILS_SUCCESS = "FETCH_METER_DETAILS_SUCCESS";
export const FETCH_METER_DETAILS_FAILURE = "FETCH_METER_DETAILS_FAILURE";

export const DELETE_METER_REQUEST = "DELETE_METER_REQUEST";
export const DELETE_METER_SUCCESS = "DELETE_METER_SUCCESS";
export const DELETE_METER_FAILURE = "DELETE_METER_FAILURE";
//---------------------------------ENTRIES TYPES--------------------------------
export const FETCH_ENTRIES_LIST_REQUEST = "FETCH_ENTRIES_LIST_REQUEST";
export const FETCH_ENTRIES_LIST_SUCCESS = "FETCH_ENTRIES_LIST_SUCCESS";
export const FETCH_ENTRIES_LIST_FAILURE = "FETCH_ENTRIES_LIST_FAILURE";

//---------------------------------FILE TYPES--------------------------------
export const FILE_UPLOAD_REQUEST = "FILE_UPLOAD_REQUEST"
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
export const FILE_UPLOAD_FAILURE = "FILE_UPLOAD_FAILURE"
