export const BASELINE_STATUS = {
  DRAFT: "DRAFT",
  CALCULATED: "CALCULATED",
  SUBMITTED: "SUBMITTED",
  REQUESTED: "REQUESTED",
  REVIEWED: "REVIEWED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
};
