export const FACILITY_ID_GENERAL_STATUS = {
  DRAFT: 0,
  CREATE_FACILIY: 1,
  ENETR_FACILITY_DATA: 2,
  SUBMIT_FACILITY: 3,
  ACCEPT_FACILITY_ENROLLEMNT: 4,
  PROGRAM_START: 5,
};

export const FACILITY_ID_SUBMISSION_STATUS = {
  DRAFT: 0,
  READY_FOR_SUBMISSION: 1,
  SUBMITTED: 2,
  IN_REVIEW: 3,
  APPROVED: 5,
  REJECTED: 6,
  BASELINE_APPROVED: 4,
  BASELINE_MODELING_STAGE: 7,
  ENROLLMENT_IN_PROGRESS_APPROVEL_PENDING: 8,
  BASELINE_PENDING_REVIEW: 9,
  BASELINE_PENDING_APPROVAL: 10,
  BASELINE_SUBMITTED: 11,
  APPLICATION_APPROVED: 12,
  P4P_1ST_PENDING: 13,
  IN_P4P_1ST: 14,
  P4P_1ST_APPROVED: 15,
  P4P_2ND_PENDING: 16,
  IN_P4P_2ND: 17,
  P4P_2ND_APPROVED: 18,
  P4P_3RD_PENDING: 19,
  IN_P4P_3RD: 20,
  P4P_3RD_APPROVED: 21,
};

export const FACILITY_APPROVAL_STATUS = {
  INITIAL: false,
  APPROVED: true,
};

export const FACILITY_TYPE = {
  CUSTOMER: 1,
  AGGREGATOR: 2,
};

export const FACILITY_CONSTRUCTION_STATUS = {
  EXISTING: 1,
  NEW_CONSTRUCTION: 2,
  TEST_FACILITy: 3,
};

export const FACILITY_METER_TYPE = {
  ELECTRICITY: 1,
  WATER: 2,
  NATURAL_GAS: 3,
};

export const FACILITY_METER_TYPE_TEXT = {
  ELECTRICITY: "Electricity",
  WATER: "Water",
  NATURAL_GAS: "Natural Gas",
};
