export enum StatusCode {
    Ok = '200',
    Created = '201',
    Accepted = '202',
    Found = '302',
    BadRequest = '400',
    Unauthorized = '401',
    PaymentRequired = '402',
    Forbidden = '403',
    NotFound = '404',
    RequestTimeout = '408',
    InternalServerError = '500',
    NotImplemented = '501',
    BadGateway = "502",
    ServiceUnavailable = '503',
    GatewayTimeout = '504',
    HttpVersionNotSupported = '505',
    InsufficientStorage = '507',    
}

export const HTTP_STATUS_CODES = {
    SUCCESS: 200,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED_ACCESS: 401,
    PAYMENT_REQUIRED: 402,
    ALREADY_EXIST: 403,
    RECORD_NOT_FOUND: 404,
    CONFLICT_ERROR: 409,
    INTERNAL_SERVER_ERROR: 500,
  };

  export const RESPONSE_MESSAGES = {
    sUCError: "SequelizeUniqueConstraintError",
    noContent: "No Content",
    singupSuccess: "Signup Success",
    Success: "Success",
    invalidJson: "Invalid JSON",
    loginSuccess: "Successfully Login",
    inccorectCreds: "Incorrect Password",
    unauthorized: "Unauthorized",
    userNotFound: "This email has not been registered. Please use a valid email id.",
    accountActive: "Account Activated Successfully",
    accountDeactive: "Account Deactivated Successfully",
    accountNotFound: "Sorry not able to fetch the account",
    notFound404: "Sorry not able to fetch the details",
    wrongPassword: "Incorrect Password",
    pUpdated: "Password Updated Successfully",
    prUpdated: "Profile Updated Successfully",
    incorrectOtp: "OTP is incorrect please try again",
    expiredOtp: "OTP is gets expired",
    accounNotActive: "Your Account is notactivated yet, verify it first",
    otpVerified: "OTP verified successfully",
    otpSent: "OTP sent successfully",
    dataUnique: "Data Should be unique",
    emailNotExist: "Please enter a registered email address",
  };